apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nodejs-lockfile-parser
  annotations:
    github.com/project-slug: snyk/nodejs-lockfile-parser
    github.com/team-slug: snyk/engines_sca-scanners
spec:
  type: external-library
  lifecycle: "-"
  owner: sca-scanners
